import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Screen from "@/components/layout/Screen";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Screen valign="center" halign="center">
          {children}
        </Screen>
      </body>
    </html>
  );
}
